import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const posts = JSON.parse(
  fs.readFileSync(path.join(root, '.tmp-raindancing-ig', 'posts-with-captions.json'), 'utf8'),
)

const versions = {
  1: 1789060470,
  2: 1789060500,
  3: 1789060503,
  4: 1789060507,
  5: 1789060511,
  6: 1789060514,
  7: 1789060518,
  8: 1789060522,
  9: 1789060526,
  10: 1789060530,
  11: 1789060533,
  12: 1789060533,
  13: 1789060544,
  14: 1789060548,
  15: 1789060551,
  16: 1789060555,
  17: 1789060559,
  18: 1789060562,
  19: 1789060567,
  20: 1789060570,
  21: 1789060574,
  22: 1789060578,
  23: 1789060582,
  24: 1789060583,
  25: 1789072015,
  26: 1789072018,
  27: 1789072023,
  28: 1789072027,
  29: 1789072032,
  30: 1789072032,
  31: 1789072064,
  32: 1789072069,
  33: 1789072073,
  34: 1789072078,
  35: 1789072082,
  36: 1789072083,
}

const works = posts.map((p, i) => {
  const n = i + 1
  const id = String(n).padStart(2, '0')
  const v = versions[n]
  return {
    shortcode: p.shortcode,
    caption: (p.caption || '').trim() || 'Untitled',
    instagramUrl: `https://www.instagram.com/p/${p.shortcode}/`,
    src: `https://res.cloudinary.com/ddcf7lxh1/image/upload/v${v}/raindancing_ig_${id}.jpg`,
    igSrc: p.src,
  }
})

const payload = {
  username: 'userjsjsjsjsjsjs333',
  profileUrl: 'https://www.instagram.com/userjsjsjsjsjsjs333/',
  updatedAt: new Date().toISOString(),
  works,
}

const jsonPath = path.join(root, 'src', 'data', 'raindancing-works.json')
fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2) + '\n')

const tsPath = path.join(root, 'src', 'data', 'raindancingWorks.ts')
const ts = `/** Auto-generated by scripts/syncRainDancing.mjs / finalizeRaindancingWorks.mjs — do not edit by hand. */
export type RaindancingWork = {
  shortcode: string
  caption: string
  instagramUrl: string
  src: string
  igSrc?: string
}

export const raindancingWorksMeta = {
  username: ${JSON.stringify(payload.username)},
  profileUrl: ${JSON.stringify(payload.profileUrl)},
  updatedAt: ${JSON.stringify(payload.updatedAt)},
} as const

export const raindancingWorks: RaindancingWork[] = ${JSON.stringify(works, null, 2)}
`
fs.writeFileSync(tsPath, ts)
console.log(`Wrote ${works.length} works`)
