/** Auto-generated by scripts/syncRainDancing.mjs — do not edit by hand. */
export type RaindancingWork = {
  shortcode: string
  caption: string
  instagramUrl: string
  src: string
  igSrc?: string
}

export const raindancingWorksMeta = {
  username: "userjsjsjsjsjsjs333",
  profileUrl: "https://www.instagram.com/userjsjsjsjsjsjs333/",
  updatedAt: "2026-09-10T20:41:06.594Z",
} as const

export const raindancingWorks: RaindancingWork[] = [
  {
    "shortcode": "Dc_3-0-ndS1",
    "caption": "మూర్ఛ (murcha)",
    "instagramUrl": "https://www.instagram.com/p/Dc_3-0-ndS1/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060470/raindancing_ig_01.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/799754854_17964459792188792_9123261534054855859_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=N0CDnkPNFHEQ7kNvwG0RMyB&_nc_oc=AdpkejDDo7XtxhK5Jbl5LCdqHxbcv8H28L8uPjVsEHqHViXo_a_gtvnZCumSmrsXuic&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQKAkEmgj4elqBm6TRdUSJFwlkGRLWYU_hlDl0jqeulqcw&oe=6AA8C316"
  },
  {
    "shortcode": "Dc_1Ks_nRuh",
    "caption": "میں نے اپنی راکھی خود باندھی اور اسے خون میں ملا دیا۔",
    "instagramUrl": "https://www.instagram.com/p/Dc_1Ks_nRuh/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060500/raindancing_ig_02.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/800258675_17964457362188792_4859142783817244056_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=vQYvHAynstUQ7kNvwFu21T3&_nc_oc=AdqjwlkzxCe6bLvoYcB4vhV76M_jHf8LvjW1w2S5NjcMn2SciP20F4-Dfs9snSQqNuY&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQIbYdeCxtwAjozCDzR9BG5joTAXsRhQbtgArVlDC66E-g&oe=6AA8D369"
  },
  {
    "shortcode": "Dc_l44sEQ-v",
    "caption": "కాలం",
    "instagramUrl": "https://www.instagram.com/p/Dc_l44sEQ-v/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060503/raindancing_ig_03.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/799543245_17964441582188792_3573479619688401418_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=pOJwrhIk8qwQ7kNvwHgmUhO&_nc_oc=AdoocrNq27ySaRFFBaj3woRKxgYUbeBzzFfIJGF-kpVJxtVE0uKesqNoWQnhqw5s5So&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQK0r0FF3Vg0kZLEomyMi1wGSr_MGF2bSwziEAokCfLnxQ&oe=6AA8C463"
  },
  {
    "shortcode": "DcpRZXvESpc",
    "caption": "ໝາກແວ່ນຂວັນ (Mak Vaen Khuan) - soul mirror",
    "instagramUrl": "https://www.instagram.com/p/DcpRZXvESpc/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060507/raindancing_ig_04.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/790059569_17963138343188792_6047296092440515919_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=-lkQJq9WeSAQ7kNvwG-BMOv&_nc_oc=Ado2oNt79nYUQ7T1RymFBRXg1qfqGAWXZm9NA95ZDakV3dIjeY2Ths3N6F-d5N_F66M&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQKpT350ITJHma_-FU9Za2e17OXTQgsvle7Z0CekOQooCA&oe=6AA8C7BD"
  },
  {
    "shortcode": "DcpPyt3EfWo",
    "caption": "جدا (juda) - separate",
    "instagramUrl": "https://www.instagram.com/p/DcpPyt3EfWo/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060511/raindancing_ig_05.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/781978434_17963137224188792_6249050930773021748_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=Eyk2rjPAzj8Q7kNvwEpeUeB&_nc_oc=AdowNMD2-1el_W_xbW8nnVP7V_9A7SuDG-pGUXYM70wF3gZ6sMWc8djG11P_Rh8PjWU&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQJV5PXEKv-nbFyiaMIOda0XH1iknr6cFw24BHnOxmcziw&oe=6AA8D7C0"
  },
  {
    "shortcode": "DcpO2-ykVaT",
    "caption": "అశాశ్వత (ashaswatha) - ephemera",
    "instagramUrl": "https://www.instagram.com/p/DcpO2-ykVaT/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060514/raindancing_ig_06.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/782511557_17963136684188792_5141181268839344909_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=063xW0VpZtMQ7kNvwFESUIE&_nc_oc=AdrsMsMNzSwTGWtf-6Rog9hHsRc7g6JWfVLEnG00srkb0xWaBBHnIaaSTS8dyp2hPYM&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQLknbAMF7cny0Cdqr6x--UpLwkScO_Pcd_8OvZJjKu5Qg&oe=6AA8B3D1"
  },
  {
    "shortcode": "DcHrR2Gndnj",
    "caption": "ຍອດເງິນ (nyod ngoen)",
    "instagramUrl": "https://www.instagram.com/p/DcHrR2Gndnj/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060518/raindancing_ig_07.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/775407029_17961064128188792_9180093255126687898_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=3_wipy2CVZcQ7kNvwGE80CD&_nc_oc=AdrV9eyW8aUH7Wifev-78RYdXGxRoC4Y-1GmQRg86PGoIlezW7DLhqiCJmRVf35YTm4&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQKwzQpIJLtSngqTZfnZGAkOjUj84JKB6qpQ5ZZ3rMJirg&oe=6AA8BBED"
  },
  {
    "shortcode": "DcHBO1BmiRD",
    "caption": "నిర్మాణం (nirmanam)",
    "instagramUrl": "https://www.instagram.com/p/DcHBO1BmiRD/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060522/raindancing_ig_08.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/774803318_17961026256188792_7786948811910861594_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=tOaJ6wejm88Q7kNvwF8tHK8&_nc_oc=AdrMFxJ2xYse86_xokN81HlEzIFHrTtfXEiyEktJH3vpT5QP5iNpZBPyi_eab5GL2E0&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQLKz9yUe9hVROGjUKYvihZnBe58rcx3iJ6y9gkSkbjwBQ&oe=6AA8C77F"
  },
  {
    "shortcode": "DcHARNMmreP",
    "caption": "పురాణం (puranam)",
    "instagramUrl": "https://www.instagram.com/p/DcHARNMmreP/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060526/raindancing_ig_09.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/775714796_17961025545188792_8315244565741346841_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=7v0yROrnkiAQ7kNvwFabYhH&_nc_oc=AdoaGyQdXEVsm-V0dZ0BFIAyFmm61hgbv12irWytxJbbzq8JBU2-gIMngdyMdW5FYrE&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQIT6KmEQJldYWi5317_Xk-Se2x-irdUMRUnuINQ20TY6w&oe=6AA8A2B9"
  },
  {
    "shortcode": "DcG_iOKGrQW",
    "caption": "స్వరాలు (Svaralu)",
    "instagramUrl": "https://www.instagram.com/p/DcG_iOKGrQW/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060530/raindancing_ig_10.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/775858414_17961024759188792_9077687516384811559_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=ZwrxvL0ZJbwQ7kNvwGrHmvY&_nc_oc=AdrnILkMdLVn8Ovs9T1z0IT01mBSTKZKoWp_P6_YysUDBIM8yqH3S1YMrz6mzKLg5UU&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQKIUL6q9qDBU7flnVXPRKRV1qOXGNgrhOuhQnZBXeSmHQ&oe=6AA8C7AD"
  },
  {
    "shortcode": "Dbi6hLZlKdT",
    "caption": "സ്വയംകൃതമായ മുറിവ്",
    "instagramUrl": "https://www.instagram.com/p/Dbi6hLZlKdT/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060533/raindancing_ig_11.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/760648339_17958708774188792_1211242013775765091_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=esLMa0Dsa6gQ7kNvwHg9dzn&_nc_oc=AdoaU2YjIc6_dcItUE93TYwhb9e7FKEk2s-ie76cJ3XFQQM_T5D9IYbFuSm_0ExDGq0&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQJz5M-1RMf7K4vXs8piNa14mwBsIMhXUm2bzNAmkBzp_A&oe=6AA8C8EE"
  },
  {
    "shortcode": "DbghWMXnbAp",
    "caption": "ചെയ്യുക (cheyukka)",
    "instagramUrl": "https://www.instagram.com/p/DbghWMXnbAp/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060533/raindancing_ig_12.jpg",
    "igSrc": "https://scontent.cdninstagram.com/v/t51.82787-15/762866999_17958543840188792_8784508394498651164_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=4wY_Z-nRGr4Q7kNvwFjYgLN&_nc_oc=AdohLG7LYicTeWFd1AgFPrOzEJbSIE6OvP9WfBnecyMe8d-x8LWMvL9P1xi00g0uxfg&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=6iX-537_FwkA5ArmRniVMw&_nc_ss=78a8c&oh=00_AQLTL46TpGWlCubJSxkn0svTN5e8AIuDA1-o1df92FkqKQ&oe=6AA8D525"
  },
  {
    "shortcode": "Dbgg9vjHXdD",
    "caption": "चेतना (chetňa)",
    "instagramUrl": "https://www.instagram.com/p/Dbgg9vjHXdD/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060544/raindancing_ig_13.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/762543454_17958543273188792_1312708955320413760_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=xdQz0yHid7EQ7kNvwFI2B0A&_nc_oc=Ado977IG9JQKBaTQOrMElSYdJCtYR0Nd80z5lyiqETlFw3vXa5sJ8fVozJ5XjhTcnio&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQIffNzC7eBZIkJRCZaJnhoVxKRUjLYNefVU0fhyVYvSdg&oe=6AA8BD1D"
  },
  {
    "shortcode": "Da4KhITlHEd",
    "caption": "त्र्यम्बकं (Thryambakam) - The Three Eyed One",
    "instagramUrl": "https://www.instagram.com/p/Da4KhITlHEd/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060548/raindancing_ig_14.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/747761072_17956058955188792_4318140536987458491_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=5Evrf9C1qBYQ7kNvwGWfutq&_nc_oc=AdpnTfIWLJ2r9ZuZR-tpaHpGDnutoWLV2YiGrEMc7R8fwwOXbJfmIMcbJ9l66SDZkT8&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQINmSRB5gA9U99EfH3vyHVQUv2r8Ouxt4IoOHm1rwcAMw&oe=6AA8B3DD"
  },
  {
    "shortcode": "Da3aBd8ErLC",
    "caption": "स्मरण (smaraņa) - remembrance",
    "instagramUrl": "https://www.instagram.com/p/Da3aBd8ErLC/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060551/raindancing_ig_15.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/749767312_17956016913188792_3465324318186597382_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=sQ2iEKs6UxMQ7kNvwFQgRSF&_nc_oc=Adp37IAj6pHyGFHhP6psbIOCGKUL4wYI26mIZkv8dox8c-eEx3Yb6Z1CoCByi0_xxqU&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQK2sJpCSyrWj81hcd7olIdJRkYedG9IKwCWtM3vqGnOIg&oe=6AA8CEC5"
  },
  {
    "shortcode": "DalvlyHD4IT",
    "caption": "కర్మ (Karma)",
    "instagramUrl": "https://www.instagram.com/p/DalvlyHD4IT/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060555/raindancing_ig_16.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/736349084_17954923707188792_5447943100617993997_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=JhqZ4NnL8XEQ7kNvwEDiAix&_nc_oc=AdoT32fov_sL2wgvHLAZ7wxy6LTCHJayu3qhCowzwjXS_6qW8AgPtlBPLeScoDhNeWM&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQLbztA4MItflnZRhgmQ2kvLKCtBGQdoC9ZlTQ_KFKKAJg&oe=6AA8B69B"
  },
  {
    "shortcode": "DajNcV-D74M",
    "caption": "రక్త బలి (Rakta Bali)",
    "instagramUrl": "https://www.instagram.com/p/DajNcV-D74M/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060559/raindancing_ig_17.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/736260684_17954775585188792_6561954567034106281_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=ujPjoW5VyRoQ7kNvwExMEwO&_nc_oc=AdqoGK9eo42yKi9oiSQHVMKAEVGF8JDOGbXEC-9QvKnLBugp-EnLNmzaCLbgO-Io5k0&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQLg-fjQAOH-TlkOCo9vI933H5k3jc4J4Mz9jOOyOcmV8A&oe=6AA8AF51"
  },
  {
    "shortcode": "DagMdIAjwq2",
    "caption": "జొల్లు (Jollu)",
    "instagramUrl": "https://www.instagram.com/p/DagMdIAjwq2/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060562/raindancing_ig_18.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/736198522_17954600400188792_7727482976264795792_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=rPggmMOKJzIQ7kNvwE5Kwgx&_nc_oc=Adqbqd5sO5kMUUISeIHDLXSJcnVQgWGzCFDnaJkUvMF5jsvumDJvFUAmjQIHDHCGqWQ&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQLstJCYBEWZ5gQ3KUTxvU0K8Q2i8RXhgpvNUnsw8STeKg&oe=6AA8A538"
  },
  {
    "shortcode": "DaBFlUzlGFP",
    "caption": "दुःख (duḥkha) - suffering",
    "instagramUrl": "https://www.instagram.com/p/DaBFlUzlGFP/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060567/raindancing_ig_19.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/728093436_17952687312188792_7881717796543395992_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=oQcuoTNl9swQ7kNvwHdpimq&_nc_oc=Adqz4OEUgfJtzSPhsqG8hfl0rw437b-0hLt5VAA1UgDWURW8j0U3AXPM1RRqRqjYj4E&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQK4nbH1hyQ04-X1pvhj74NnpPOsh62nI7rHMpm5LQMyoA&oe=6AA8CA43"
  },
  {
    "shortcode": "DZ2_sOaj5cW",
    "caption": "अस्वस्थ (a-svas-tha) - indisposed",
    "instagramUrl": "https://www.instagram.com/p/DZ2_sOaj5cW/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060570/raindancing_ig_20.jpg",
    "igSrc": "https://scontent-dfw5-3.cdninstagram.com/v/t51.82787-15/728622654_17952075720188792_1210031005955671852_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=IeS-x9g1JFcQ7kNvwGgbLK8&_nc_oc=AdoRcE1VZxzkNJBIjaRSySoU7qDhsGKqOAb_9zf5WZdMjO5nqmzTzGxu69TlXqZC__g&_nc_zt=23&_nc_ht=scontent-dfw5-3.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQLW6pIt0mtfCt9_kb1kvnQftTHRZhL-OGvMIp65u8zgCg&oe=6AA8B2F5"
  },
  {
    "shortcode": "DZS9GBWEt1L",
    "caption": "नाडि (nādī) - conduit",
    "instagramUrl": "https://www.instagram.com/p/DZS9GBWEt1L/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060574/raindancing_ig_21.jpg",
    "igSrc": "https://scontent-dfw5-3.cdninstagram.com/v/t51.82787-15/718698783_17949923226188792_8702671809067205605_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=Bym-xBU9CsoQ7kNvwHwxVFG&_nc_oc=AdoPqJIg9heVp_edyDteJKWMLtvE2QndUZ4g4E3O3JT2JMUk5fVGjVM-swFa-F-nyuc&_nc_zt=23&_nc_ht=scontent-dfw5-3.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQKMJAhhgNHg7JnrSTcj0G8hKRIiRPBqw_7PSHWgz9VY8A&oe=6AA8B548"
  },
  {
    "shortcode": "DZNtIvunQuo",
    "caption": "विषादक्लेश (viṣāda-kleśa) - muted grief",
    "instagramUrl": "https://www.instagram.com/p/DZNtIvunQuo/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060578/raindancing_ig_22.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/715263694_17949618915188792_6473709583548185560_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=oqKu0lX7RqsQ7kNvwGiLHw_&_nc_oc=AdpPAIahwxYLyrdJ0ckK9GlaRAIbQcZvOIJqcgppw7PIeA19GhWsGaYpTTOoxUf5q30&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQLTjCJtLJEeicq-5v4hE1j67u0boCj6IhdQhP0pK__hfA&oe=6AA8D0ED"
  },
  {
    "shortcode": "DZNsYhznRMs",
    "caption": "क्षान्ति (kshanti) - patience",
    "instagramUrl": "https://www.instagram.com/p/DZNsYhznRMs/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060582/raindancing_ig_23.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/718076146_17949618696188792_6599016006568345678_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=mGh0EqSxnAIQ7kNvwFKwHUC&_nc_oc=AdrSFZGkjWb-iuafwKORLeBmT7obO845B_YK0id9EUWcHvqpqMkWvw1FGBt9ssnuicQ&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQK66DmcIeLiGY62M5XRqTP-DM4CmSTQjt6J7wHDJzSlJA&oe=6AA8C801"
  },
  {
    "shortcode": "DZMBm-6lDfO",
    "caption": "भस्मक (bhasmaka) - polyphagia",
    "instagramUrl": "https://www.instagram.com/p/DZMBm-6lDfO/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789060583/raindancing_ig_24.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/717993461_17949512304188792_1324986825810578323_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=4yhgIpHJQFcQ7kNvwEd4JR6&_nc_oc=AdosdsSyHTlq1KcJ8IN21KdJWheo4kKTWOVuwwtWoTRSb1NqNYMGQTTfo8PrtasXVI0&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=XvGXQ0ht6py-4xsd8dndVw&_nc_ss=7aa8c&oh=00_AQJDki_u04YqRi5Ceb654DDc3Q7dhH6-T7YtC_P_EEnAGg&oe=6AA8AA3D"
  },
  {
    "shortcode": "DY80KUOFd8e",
    "caption": "నాశనం (naashanam) - ruin",
    "instagramUrl": "https://www.instagram.com/p/DY80KUOFd8e/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072015/raindancing_ig_25.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/710432095_17948585901188792_7142174796687929430_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=0MNkIS5c1O0Q7kNvwHszL2d&_nc_oc=AdqjmWSDO3rsi-7ClZZdubkHgqa1rCkuf1MeT3O7wy2EyrxJfA0e98GBhdWejU8EJTs&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQJMydgevHB4N5esCLPTDbaoRAOgYX223lasoj55t-EgiQ&oe=6AA8CFBB"
  },
  {
    "shortcode": "DY8XAFLHWwE",
    "caption": "हिंसा (hiṃsā) - violence",
    "instagramUrl": "https://www.instagram.com/p/DY8XAFLHWwE/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072018/raindancing_ig_26.jpg",
    "igSrc": "https://scontent-dfw5-3.cdninstagram.com/v/t51.82787-15/710020452_17948562759188792_3568087261753800858_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=z8BERfb88y0Q7kNvwFICSJj&_nc_oc=Adp-sNbFW6-qgOF3af-3yRXOQRQTKIx4JWTHeCX6Qq_vn9XDzUXVP9-YbNqgcy8dTQI&_nc_zt=23&_nc_ht=scontent-dfw5-3.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQKeKThNQWr2pKs-Amb8-PVtpG40VO4vyqGBPbCi7bkevg&oe=6AA8B08E"
  },
  {
    "shortcode": "DY8WSQ0na0K",
    "caption": "Untitled",
    "instagramUrl": "https://www.instagram.com/p/DY8WSQ0na0K/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072023/raindancing_ig_27.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/709092623_17948562321188792_2717640034088558958_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=-xR1GHMwTzQQ7kNvwHCvjpr&_nc_oc=AdoaviWc_eazmLOWiEOp9pLcm8TSIHuGrgx5IHnmFbMz4zzbKrSeukscHlwTlCwYaC0&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQK1Fpmw3e2ejOr06zDV8wIpHinvhbAao-OGVxv9cF1sYw&oe=6AA8AA33"
  },
  {
    "shortcode": "DYz_rqQnWam",
    "caption": "अर्पिता (arpitha) - surrender",
    "instagramUrl": "https://www.instagram.com/p/DYz_rqQnWam/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072027/raindancing_ig_28.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/707796633_17948069178188792_1208773668835602195_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=BWu4MZYHEJEQ7kNvwETgMpa&_nc_oc=Adq-VHgkorHhVzLoyIrkTm5GErPGmTHgUCoiw-cs2Oz4h3NZ5MZfL5ooNfqYY9nvt60&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQKaaDUwUX61bp5OCHJfcZE7Kw4RFxFc2gdcZk1CGGsw3Q&oe=6AA8AD28"
  },
  {
    "shortcode": "DWg5oBYGgqX",
    "caption": "निरर्थक (nirarthaka) - meaninglessness",
    "instagramUrl": "https://www.instagram.com/p/DWg5oBYGgqX/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072032/raindancing_ig_29.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/657669104_17939458596188792_4706708339614232119_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=n1BG4C_9YwIQ7kNvwHbmHgV&_nc_oc=AdqgD6NJ_HEO4k3-zFCKsn2FHIgL_gYub1qzTFvaumjmU8jnk8ehC-pH1_v6YD3qVII&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQJ0Gg880KOim2v02dNlUmP97HheIrOoy10BldyCRdIwrw&oe=6AA8ABA9"
  },
  {
    "shortcode": "DVB-esykggk",
    "caption": "प्रकृति (prakṛti) - natural",
    "instagramUrl": "https://www.instagram.com/p/DVB-esykggk/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072032/raindancing_ig_30.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/640000604_17933913570188792_2261207591738154434_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=Qv9T0scEsI0Q7kNvwHEEjIc&_nc_oc=AdrgrmP-ObShVt0_Sr-8rntSwuv7s9JRBJkpeIhP_Z3gDxlL3xkQdXgFk3_Pt2Coaag&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQIb1wisuh4YN7VaS_Rkr_wWio1uv41EjmEwq2h9bee2kQ&oe=6AA8C817"
  },
  {
    "shortcode": "DVB76VIkq2D",
    "caption": "समृद्धि (samṛddhi) - abundance",
    "instagramUrl": "https://www.instagram.com/p/DVB76VIkq2D/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072064/raindancing_ig_31.jpg",
    "igSrc": "https://scontent-dfw6-2.cdninstagram.com/v/t51.82787-15/639749604_17933910477188792_3863877342542913520_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=gt1PU7qav14Q7kNvwGng5ys&_nc_oc=AdqD1EPkMSn9_yMZTxy1rSbhYsOb8Vn_HULXnPvbd0ZY2h3ePkr_4rjPWmIFt_Nesto&_nc_zt=23&_nc_ht=scontent-dfw6-2.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQJ5UPiUXwLh3Lf2HgGsM6omMlNO6VvIkaZEIyza4l_swg&oe=6AA8C50D"
  },
  {
    "shortcode": "DU4IzN8kURK",
    "caption": "सांकर्य (sāṃkarya) - confusion",
    "instagramUrl": "https://www.instagram.com/p/DU4IzN8kURK/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072069/raindancing_ig_32.jpg",
    "igSrc": "https://scontent-dfw5-3.cdninstagram.com/v/t51.82787-15/632562425_17933442123188792_2779601449881876458_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=JpctyxUKixgQ7kNvwFwSlxs&_nc_oc=Adpy1fVIrzefH8LXTZ037ZKSgNKIoHo092_zMZf0UqJqatMSF-tLicK8D1uW1jMCAac&_nc_zt=23&_nc_ht=scontent-dfw5-3.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQK_fBwqLy5QwLF6JNOg2QYqgG97UCF0y5NlgkZalhtVGA&oe=6AA8D139"
  },
  {
    "shortcode": "DU4IX0cESkI",
    "caption": "द्रोह (droh) - malevolence",
    "instagramUrl": "https://www.instagram.com/p/DU4IX0cESkI/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072073/raindancing_ig_33.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/634409209_17933441316188792_4830313813214505517_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=IzcAMuGm9yoQ7kNvwGArjVz&_nc_oc=AdpRfpSISRN5GFkc865oMUtwGaj0T8HtbapnXnxZXS7tggAz3f3ie2WElneoWEtKSyw&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQLFovQyirt3a5fvdLpxssiBCTmC_OB3qvSJbcNVO0QY_w&oe=6AA8A4D6"
  },
  {
    "shortcode": "DU4Gi7nkYO7",
    "caption": "मेला (mela) - union",
    "instagramUrl": "https://www.instagram.com/p/DU4Gi7nkYO7/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072078/raindancing_ig_34.jpg",
    "igSrc": "https://scontent-dfw6-1.cdninstagram.com/v/t51.82787-15/634521126_17933440869188792_4183048460006666391_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=P1gD9dao1WYQ7kNvwG4gLap&_nc_oc=AdquCUatwoBMp3V74jXZWLpOZ9J44nYyf3gPloIdOZU1d3wGyVEc2bsioYYyIZwARIc&_nc_zt=23&_nc_ht=scontent-dfw6-1.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQINQGWQrgxF3uuXKwnfk8YIXzatO8Vzaw0yEobKWZNADw&oe=6AA8AEDA"
  },
  {
    "shortcode": "DUWsQPAktAq",
    "caption": "सृजा (sruja) - creation",
    "instagramUrl": "https://www.instagram.com/p/DUWsQPAktAq/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072082/raindancing_ig_35.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/625353354_17931889221188792_3739886501487705081_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=SLUtiAbrl38Q7kNvwGSobeY&_nc_oc=AdqegSjulsA5gk3rH1LbDj6yGbrMo0JfLW78Y-ImxyDevZO08TB9Rnb7SkOW44ivxSk&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQIZOe1xVX3AkFsZXVpCnejE8DIuQB8unhJwTnU3XAyjNg&oe=6AA8A460"
  },
  {
    "shortcode": "DTrnzN8Eap4",
    "caption": "अदिति (aditi) - purity",
    "instagramUrl": "https://www.instagram.com/p/DTrnzN8Eap4/",
    "src": "https://res.cloudinary.com/ddcf7lxh1/image/upload/v1789072083/raindancing_ig_36.jpg",
    "igSrc": "https://scontent-dfw5-2.cdninstagram.com/v/t51.82787-15/618892338_17929935156188792_5331573673395622391_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=aynSQWlvPxcQ7kNvwFaIAWl&_nc_oc=Adq2guuYql-vykiKgEu_WQCrozHRQQuIcMMsI676oTrWSUJkQnndgllj8Oq_EbeBFnU&_nc_zt=23&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_gid=S20CPnAsW0YfU9GatjyAOg&_nc_ss=7aa8c&oh=00_AQKxMXVFQxXpdImnW1KTgsksnp5wLG_eJ4pn7Ws9LW4BEw&oe=6AA8CEBE"
  }
]
